### ISSUE TITLE
Define .gitignore file

### ISSUE THREAD

**Issue by vondacho** [serenity-bdd/serenity-gradle-plugin#3]
To add a `.gitignore` file to the project.
- including usual `build` or `target` folders

**Comment by vondacho** [comment]
@wakaleo
While trying to propose a PR for publication on the Gradle portal, I noticed that the `.gitignore` file would be useful. Finally, I was unable to push a new branch with the intention of making a PR.

**Comment by wakaleo** [comment]
It's a public repo so you should be able to create a fork and raise a PR - you won't be able to push commits directly to the repo though (this is normal), but PRs should work.

**Comment by vondacho** [comment]
@wakaleo 
Ok, fine. And, do you agree with my proposal to publish the plugin on the Gradle portal (see next issue)?

**Comment by wakaleo** [comment]
In principle yes. I don't know when I'll get round to setting it up though.

**Comment by vondacho** [comment]
Well, with a Gradle account in place, and with my instructions in the issue, it is a couple of minutes. Then, Gradle engineers have to approve it.
