### ISSUE TITLE
ClearHistory (and ClearReports) missing Constructor

### ISSUE THREAD

**Issue by zeners** [serenity-bdd/serenity-gradle-plugin#31]
current version 4.1.6 can't create ClearHistoryTask

```
Could not create task ':clearHistory'.
Could not create task of type 'ClearHistoryTask'.
net.serenitybdd.plugins.gradle.SerenityAbstractTask: method 'void <init>()' not found

```

seems that the classes ClearHistoryTask and ClearReports use (not existing) setter `updateProperties`
after checkout current master, these classes didn't compile

running with gradle 8.7 (if that matters)

edit:
looks like the merge 3424830cb766d87cc669524396988cb8dc9dd444 undo the revert of configuration-cache compatibility c7e03104d352446d0b4b8a80094075b3c762b6c7 but missed undo-revert of the 2 classes

i can confirm, that aggregate of version 4.1.3 don't generate reports for re-runned test

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by zeners** [comment]
do you need help in get it work with gradle caching?

**Comment by wakaleo** [comment]
I don't use Gradle so any help maintaining the Gradle plugin would be most welcome

**Comment by wakaleo** [comment]
@zeners I have fixed the compilation issues and removed the history task (which no longer exists in Serenity) - not sure about the report regeneration, maybe you can investigate this on your side?

**Comment by zeners** [comment]
@wakaleo thank you, i'm working on it

**Comment by zeners** [comment]
solved with 164585be3481383d8532fa90e2b42b3502b23e21

**Comment by petrandreev** [comment]
@zeners :
regarding reports not generated: just tried to set generateOutcomes (boolean, not initialized, e.g. -> false):
serenity {
    generateOutcomes = true
}
Reports are generated.

Another thing - one needs also to remove history-related tasks registration from SerenityPlugin, the plugin can't be initalized otherwise:
<img width="1232" alt="image" src="https://github.com/serenity-bdd/serenity-gradle-plugin/assets/5670574/a196ec23-9ff6-411f-bcf9-af149d5a941a">

**Comment by zeners** [comment]
@petrandreev confirmed: def clearHistory and def history has to be removed

now i have a dev environment to test the plugin

may you have a source for `serenity { generateOutcomes = true }`, in the past, it wasn't required
